apiVersion: v1
kind: Service
metadata:
  name: marketplace
  labels:
    app: marketplace
    service: marketplace
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30888
    name: http
  selector:
    app: marketplace
---